---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-installation"
      label: "Installation"
      solveButton: false
    - name: "02-login"
      label: "Login"
      solveButton: false
    - name: "03-blueprint"
      label: "Blueprint"
      solveButton: false
    - name: "04-image"
      label: "Image"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty_rhel/ssh/root
  - name: "RHEL Web Console"
    url: https://cockpit-${guid}.${domain}/
